import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from './auth/AuthProvider';
import './globals.css';
import NavBar from './NavBar';
import QueryClientProvider from './QueryClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Issue Tracker App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <QueryClientProvider>
                    <AuthProvider>
                        <NavBar />
                        {children}
                        <Toaster />
                    </AuthProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
